---
- name: Check Security updates only
  hosts: sgp3vpnlp00001.vpn.cdom

  tasks:
  - name: list available security patches.
    yum:
      name: '*'
      security: yes
      state: latest
    check_mode: yes
    register: yum_output

  - name: show that yum output
    debug:
      msg: "{{ yum_output }}"