---
- name: Copy file to ansible managed nodes
  hosts: all

  tasks:
  - name: Copy 'file_from_orakvm' to managed nodes
    #become: true
    copy:
      src: /home/sysadm/ansible/files/file_from_orakvm
      dest: /root
      owner: sysadm
      group: wheel
      mode: 0640