---
- name: Update/change user password.
  hosts: all

  tasks:
  - name: Update passwd for john
    user:
      name: john
      update_password: always
      password: "{{ newpassword|password_hash('sha512') }}"
