---
- name: Install Apache Webserver
  hosts: all

  tasks: 
  - name: Install Apache on Ubuntu Server
    apt: 
      name: apache2
      state: present
    when: ansible_os_family == "Ubuntu"

  - name: Install Apache on CentOs Server
    yum: 
     name: httpd
     state: present
    when: ansible_os_family == "RedHat"