---
- name: Create users thru loop
  hosts: localhost

  tasks: 
  - name: Create users
    user: 
      name: "{{ item }}"
    loop:
      - jerry
      - kramer
      - eliane

  - name: Remove users
    user:
      name: "{{ item }}"
      remove: true
      state: absent
    loop:
      - jerry
      - kramer
      - eliane