---
- name: Create users thru loop
  hosts: localhost
  vars: 
    users: [john,jaffer,janardhan]

  tasks:
  - name: Create users
    user: 
      name: '{{item}}'
    with_items: '{{users}}'

  - name: Remove users
    user: 
      name: '{{item}}'
      state: absent
      remove: true
    with_items: '{{users}}'
